
INSERT INTO lab_reports (patient_id, report_type, specimen_type, specimen_date, status, uploaded_by, reviewed_by, organisms, sensitivities, is_mdr, mdr_type, ocr_processed, medical_summary, doctor_notes) VALUES

('ab05247a-375c-49e5-bf77-2d7021052680', 'urine_test', 'Mid-stream urine', NOW() - INTERVAL '3 days', 'confirmed', '3957f788-3d0a-4d3a-ad3d-ea66dfe0876a', '4e04482c-dd3c-4507-9802-7eab873aff2a',
'[{"name": "Escherichia coli", "colony_count": ">10^5 CFU/ml"}]'::jsonb,
'[{"antibiotic": "Nitrofurantoin", "sensitivity": "Sensitive", "mic": "16"}, {"antibiotic": "Ciprofloxacin", "sensitivity": "Sensitive", "mic": "0.25"}, {"antibiotic": "Amoxicillin", "sensitivity": "Resistant", "mic": ">32"}, {"antibiotic": "Cotrimoxazole", "sensitivity": "Resistant", "mic": ">4"}, {"antibiotic": "Cephalexin", "sensitivity": "Sensitive", "mic": "4"}]'::jsonb,
false, NULL, true,
'Uncomplicated UTI. E.coli isolated, sensitive to nitrofurantoin. Community-acquired, no risk factors.',
'Simple UTI. Started on Nitrofurantoin 100mg BD for 5 days. Follow-up urine culture after completion.'),

('3a991be5-7bfe-4e13-96b1-b00b6c2692f0', 'culture_sensitivity', 'Blood (peripheral + central line)', NOW() - INTERVAL '9 days', 'confirmed', '3957f788-3d0a-4d3a-ad3d-ea66dfe0876a', '4e04482c-dd3c-4507-9802-7eab873aff2a',
'[{"name": "Klebsiella pneumoniae", "colony_count": "Positive in 2/2 sets"}]'::jsonb,
'[{"antibiotic": "Meropenem", "sensitivity": "Sensitive", "mic": "1"}, {"antibiotic": "Piperacillin-Tazobactam", "sensitivity": "Resistant", "mic": ">128"}, {"antibiotic": "Ceftriaxone", "sensitivity": "Resistant", "mic": ">64"}, {"antibiotic": "Amikacin", "sensitivity": "Intermediate", "mic": "32"}, {"antibiotic": "Ciprofloxacin", "sensitivity": "Resistant", "mic": ">4"}, {"antibiotic": "Colistin", "sensitivity": "Sensitive", "mic": "1"}, {"antibiotic": "Tigecycline", "sensitivity": "Sensitive", "mic": "1"}]'::jsonb,
true, ARRAY['ESBL'], true,
'ESBL-producing Klebsiella pneumoniae bacteremia. Resistant to 3rd gen cephalosporins and piperacillin-tazobactam. Sensitive to carbapenems.',
'Escalated to Meropenem 1g TDS IV after failed empiric Pip-Taz. Monitor CRP and repeat blood cultures at 48-72hrs.'),

('8539c2a2-6af1-40dd-98ec-76686cffc5c0', 'culture_sensitivity', 'Sputum', NOW() - INTERVAL '6 days', 'pending', '3957f788-3d0a-4d3a-ad3d-ea66dfe0876a', NULL,
'[{"name": "Streptococcus pneumoniae", "colony_count": "Heavy growth"}]'::jsonb,
'[{"antibiotic": "Amoxicillin-Clavulanate", "sensitivity": "Sensitive", "mic": "2"}, {"antibiotic": "Azithromycin", "sensitivity": "Sensitive", "mic": "0.25"}, {"antibiotic": "Levofloxacin", "sensitivity": "Sensitive", "mic": "1"}, {"antibiotic": "Penicillin", "sensitivity": "Intermediate", "mic": "2"}, {"antibiotic": "Ceftriaxone", "sensitivity": "Sensitive", "mic": "0.5"}]'::jsonb,
false, NULL, true,
'Community-acquired pneumonia. S. pneumoniae isolated from sputum. Sensitive to amoxicillin-clavulanate.',
NULL),

('7c0ec9ce-40dd-4d0d-aefd-936ce62abd22', 'culture_sensitivity', 'Blood (central line)', NOW() - INTERVAL '13 days', 'confirmed', '3957f788-3d0a-4d3a-ad3d-ea66dfe0876a', '4e04482c-dd3c-4507-9802-7eab873aff2a',
'[{"name": "Acinetobacter baumannii", "colony_count": "Positive in 3/3 sets"}, {"name": "Candida albicans", "colony_count": "Positive in 1/3 sets"}]'::jsonb,
'[{"antibiotic": "Colistin", "sensitivity": "Sensitive", "mic": "0.5"}, {"antibiotic": "Meropenem", "sensitivity": "Resistant", "mic": ">16"}, {"antibiotic": "Imipenem", "sensitivity": "Resistant", "mic": ">16"}, {"antibiotic": "Ceftazidime", "sensitivity": "Resistant", "mic": ">64"}, {"antibiotic": "Ciprofloxacin", "sensitivity": "Resistant", "mic": ">4"}, {"antibiotic": "Amikacin", "sensitivity": "Resistant", "mic": ">64"}, {"antibiotic": "Piperacillin-Tazobactam", "sensitivity": "Resistant", "mic": ">128"}, {"antibiotic": "Tigecycline", "sensitivity": "Intermediate", "mic": "4"}, {"antibiotic": "Fluconazole", "sensitivity": "Sensitive (Candida)", "mic": "2"}]'::jsonb,
true, ARRAY['PDR','CRE'], true,
'Pan-drug resistant Acinetobacter baumannii with concomitant Candida albicans candidemia. Only colistin sensitive for A. baumannii.',
'Started Colistin 9MU loading then 4.5MU BD + Fluconazole 400mg OD. Candida cleared after 7 days.'),

('7c0ec9ce-40dd-4d0d-aefd-936ce62abd22', 'blood_test', 'Venous blood', NOW() - INTERVAL '12 days', 'reviewed', '3957f788-3d0a-4d3a-ad3d-ea66dfe0876a', '4e04482c-dd3c-4507-9802-7eab873aff2a',
'[]'::jsonb, '[]'::jsonb,
false, NULL, true,
'WBC: 22,000/mm3, Neutrophils: 89%, CRP: 285 mg/L, Procalcitonin: 18.5 ng/mL, Lactate: 4.2 mmol/L, Creatinine: 3.1 mg/dL (AKI).',
'Sepsis with multi-organ dysfunction. AKI - adjust antibiotic dosing for renal impairment.'),

('3a866a04-abbe-4463-a94c-2618b2c5c190', 'culture_sensitivity', 'Wound swab', NOW() - INTERVAL '2 days', 'confirmed', '3957f788-3d0a-4d3a-ad3d-ea66dfe0876a', '4e04482c-dd3c-4507-9802-7eab873aff2a',
'[{"name": "Staphylococcus aureus (MSSA)", "colony_count": "Heavy growth"}]'::jsonb,
'[{"antibiotic": "Cephalexin", "sensitivity": "Sensitive", "mic": "2"}, {"antibiotic": "Cloxacillin", "sensitivity": "Sensitive", "mic": "0.5"}, {"antibiotic": "Clindamycin", "sensitivity": "Sensitive", "mic": "0.25"}, {"antibiotic": "Cotrimoxazole", "sensitivity": "Sensitive", "mic": "1"}, {"antibiotic": "Oxacillin", "sensitivity": "Sensitive", "mic": "1"}]'::jsonb,
false, NULL, true,
'MSSA wound infection. All first-line anti-staphylococcal agents sensitive.',
'Cephalexin 500mg QID oral for 7 days. No need for IV therapy.'),

('806c5b39-e331-4d68-9e67-7670a06de0e6', 'culture_sensitivity', 'Peritoneal fluid', NOW() - INTERVAL '11 days', 'confirmed', '3957f788-3d0a-4d3a-ad3d-ea66dfe0876a', '4e04482c-dd3c-4507-9802-7eab873aff2a',
'[{"name": "Escherichia coli", "colony_count": "Moderate growth"}, {"name": "Bacteroides fragilis", "colony_count": "Moderate growth (anaerobic)"}]'::jsonb,
'[{"antibiotic": "Piperacillin-Tazobactam", "sensitivity": "Sensitive", "mic": "4"}, {"antibiotic": "Ciprofloxacin", "sensitivity": "Sensitive", "mic": "0.5"}, {"antibiotic": "Metronidazole", "sensitivity": "Sensitive (Bacteroides)", "mic": "1"}, {"antibiotic": "Meropenem", "sensitivity": "Sensitive", "mic": "0.25"}, {"antibiotic": "Ceftriaxone", "sensitivity": "Sensitive", "mic": "1"}, {"antibiotic": "Amikacin", "sensitivity": "Sensitive", "mic": "4"}]'::jsonb,
false, NULL, true,
'Mixed aerobic-anaerobic intra-abdominal infection. E.coli + Bacteroides fragilis.',
'De-escalated to oral Ciprofloxacin + Metronidazole after 5 days IV. Patient discharged.'),

('4d8a692c-34c4-4d90-b2c8-8f25f2bcee8c', 'culture_sensitivity', 'Nasopharyngeal swab', NOW() - INTERVAL '4 days', 'confirmed', '3957f788-3d0a-4d3a-ad3d-ea66dfe0876a', '4e04482c-dd3c-4507-9802-7eab873aff2a',
'[{"name": "Haemophilus influenzae", "colony_count": "Moderate growth"}]'::jsonb,
'[{"antibiotic": "Amoxicillin", "sensitivity": "Sensitive", "mic": "0.5"}, {"antibiotic": "Amoxicillin-Clavulanate", "sensitivity": "Sensitive", "mic": "1"}, {"antibiotic": "Ceftriaxone", "sensitivity": "Sensitive", "mic": "0.12"}, {"antibiotic": "Azithromycin", "sensitivity": "Sensitive", "mic": "2"}, {"antibiotic": "Cotrimoxazole", "sensitivity": "Resistant", "mic": ">4"}]'::jsonb,
false, NULL, true,
'Pediatric RTI. H. influenzae (non-beta-lactamase producing). Sensitive to amoxicillin.',
'5-year-old with community-acquired RTI. Amoxicillin 250mg TDS for 5 days.'),

('95170a50-c8ae-4d8c-a4fb-75540c6114e8', 'culture_sensitivity', 'Cerebrospinal fluid (CSF)', NOW() - INTERVAL '8 days', 'confirmed', '3957f788-3d0a-4d3a-ad3d-ea66dfe0876a', '4e04482c-dd3c-4507-9802-7eab873aff2a',
'[{"name": "Staphylococcus aureus (MRSA)", "colony_count": "Positive (CSF)"}]'::jsonb,
'[{"antibiotic": "Vancomycin", "sensitivity": "Sensitive", "mic": "1"}, {"antibiotic": "Linezolid", "sensitivity": "Sensitive", "mic": "2"}, {"antibiotic": "Rifampicin", "sensitivity": "Sensitive", "mic": "0.06"}, {"antibiotic": "Oxacillin", "sensitivity": "Resistant", "mic": ">4"}, {"antibiotic": "Clindamycin", "sensitivity": "Resistant", "mic": ">4"}, {"antibiotic": "Ciprofloxacin", "sensitivity": "Resistant", "mic": ">4"}, {"antibiotic": "Cotrimoxazole", "sensitivity": "Sensitive", "mic": "1"}]'::jsonb,
true, ARRAY['MRSA'], true,
'MRSA meningitis in immunocompromised patient. CSF WBC: 1200, Protein: 380mg/dL, Glucose: 18mg/dL.',
'Vancomycin 1g BD IV with trough monitoring. 21-day course. Dose adjusted for renal impairment.'),

('95170a50-c8ae-4d8c-a4fb-75540c6114e8', 'blood_test', 'Venous blood', NOW() - INTERVAL '7 days', 'reviewed', '3957f788-3d0a-4d3a-ad3d-ea66dfe0876a', '4e04482c-dd3c-4507-9802-7eab873aff2a',
'[]'::jsonb, '[]'::jsonb,
false, NULL, true,
'WBC: 18,500/mm3, CRP: 190 mg/L, Procalcitonin: 5.2 ng/mL, Creatinine: 2.4 mg/dL, Vancomycin trough: 14.8 mcg/mL.',
'Vancomycin trough subtherapeutic. Increased dose to 1.25g BD.'),

('486fa732-8e69-4b7a-8dae-7a14a5e307a9', 'urine_test', 'Mid-stream urine', NOW() - INTERVAL '7 days', 'confirmed', '4e04482c-dd3c-4507-9802-7eab873aff2a', '4e04482c-dd3c-4507-9802-7eab873aff2a',
'[{"name": "Escherichia coli", "colony_count": ">10^5 CFU/ml"}]'::jsonb,
'[{"antibiotic": "Ciprofloxacin", "sensitivity": "Sensitive", "mic": "0.25"}, {"antibiotic": "Nitrofurantoin", "sensitivity": "Sensitive", "mic": "16"}, {"antibiotic": "Ceftriaxone", "sensitivity": "Sensitive", "mic": "0.5"}, {"antibiotic": "Amoxicillin", "sensitivity": "Resistant", "mic": ">32"}, {"antibiotic": "Cotrimoxazole", "sensitivity": "Sensitive", "mic": "1"}]'::jsonb,
false, NULL, true,
'Uncomplicated UTI with E.coli. Good sensitivity to ciprofloxacin.',
'Ciprofloxacin 500mg BD for 5 days. Patient discharged.'),

('d3511243-9b47-4a3c-a764-d83eb458259a', 'culture_sensitivity', 'Blood (peripheral + central line)', NOW() - INTERVAL '16 days', 'confirmed', '3957f788-3d0a-4d3a-ad3d-ea66dfe0876a', '4e04482c-dd3c-4507-9802-7eab873aff2a',
'[{"name": "Klebsiella pneumoniae (CRE)", "colony_count": "Positive in 3/3 sets"}]'::jsonb,
'[{"antibiotic": "Ceftazidime-Avibactam", "sensitivity": "Sensitive", "mic": "4"}, {"antibiotic": "Meropenem", "sensitivity": "Resistant", "mic": ">16"}, {"antibiotic": "Imipenem", "sensitivity": "Resistant", "mic": ">16"}, {"antibiotic": "Colistin", "sensitivity": "Sensitive", "mic": "1"}, {"antibiotic": "Tigecycline", "sensitivity": "Sensitive", "mic": "1"}, {"antibiotic": "Piperacillin-Tazobactam", "sensitivity": "Resistant", "mic": ">128"}, {"antibiotic": "Ciprofloxacin", "sensitivity": "Resistant", "mic": ">4"}, {"antibiotic": "Amikacin", "sensitivity": "Resistant", "mic": ">64"}]'::jsonb,
true, ARRAY['CRE','ESBL'], true,
'CRE Klebsiella pneumoniae bacteremia. Only ceftazidime-avibactam, colistin, tigecycline sensitive.',
'Meropenem REJECTED. Escalated to Ceftazidime-Avibactam 2.5g TDS IV.'),

('d3511243-9b47-4a3c-a764-d83eb458259a', 'blood_test', 'Venous blood', NOW() - INTERVAL '14 days', 'reviewed', '3957f788-3d0a-4d3a-ad3d-ea66dfe0876a', '4e04482c-dd3c-4507-9802-7eab873aff2a',
'[]'::jsonb, '[]'::jsonb,
false, NULL, true,
'WBC: 25,800/mm3, Neutrophils: 92%, CRP: 320 mg/L, Procalcitonin: 25.1 ng/mL, Lactate: 5.8 mmol/L, Creatinine: 3.8 mg/dL.',
'Severe sepsis with AKI Stage 3. Nephrology consult for possible dialysis.'),

('41ce1076-cf50-4ad7-ab3e-49c5b3242026', 'culture_sensitivity', 'Wound swab (abscess)', NOW() - INTERVAL '1 day', 'pending', '3957f788-3d0a-4d3a-ad3d-ea66dfe0876a', NULL,
'[{"name": "Streptococcus pyogenes (Group A)", "colony_count": "Heavy growth"}]'::jsonb,
'[{"antibiotic": "Ceftriaxone", "sensitivity": "Sensitive", "mic": "0.12"}, {"antibiotic": "Penicillin", "sensitivity": "Sensitive", "mic": "0.06"}, {"antibiotic": "Clindamycin", "sensitivity": "Sensitive", "mic": "0.12"}, {"antibiotic": "Mupirocin", "sensitivity": "Sensitive (topical)", "mic": "0.25"}, {"antibiotic": "Erythromycin", "sensitivity": "Sensitive", "mic": "0.25"}]'::jsonb,
false, NULL, true,
'Group A Streptococcus wound abscess. Fully sensitive to beta-lactams.',
NULL),

('f7d7fb13-247c-487d-b157-2caa1655c793', 'culture_sensitivity', 'Peritoneal fluid (drain)', NOW() - INTERVAL '5 days', 'confirmed', '4e04482c-dd3c-4507-9802-7eab873aff2a', '4e04482c-dd3c-4507-9802-7eab873aff2a',
'[{"name": "Escherichia coli (ESBL)", "colony_count": "Heavy growth"}, {"name": "Enterococcus faecalis", "colony_count": "Moderate growth"}]'::jsonb,
'[{"antibiotic": "Metronidazole", "sensitivity": "Sensitive (anaerobic cover)", "mic": "1"}, {"antibiotic": "Meropenem", "sensitivity": "Sensitive", "mic": "0.25"}, {"antibiotic": "Piperacillin-Tazobactam", "sensitivity": "Intermediate", "mic": "64"}, {"antibiotic": "Ciprofloxacin", "sensitivity": "Resistant", "mic": ">4"}, {"antibiotic": "Ceftriaxone", "sensitivity": "Resistant", "mic": ">64"}, {"antibiotic": "Amikacin", "sensitivity": "Sensitive", "mic": "4"}, {"antibiotic": "Ampicillin", "sensitivity": "Sensitive (Enterococcus)", "mic": "2"}]'::jsonb,
true, ARRAY['ESBL'], true,
'ESBL E.coli + Enterococcus faecalis intra-abdominal infection. Renal impairment - avoid aminoglycosides.',
'Metronidazole 500mg TDS IV for anaerobic cover. Consider adding Ampicillin for Enterococcal coverage.');
